harvard-lil/capstone-static

components/cap-decorated-header.js, css/fonts.css, index.html
Change was to update the folder locations of the JS, CSS, font, and image source paths. 
GitHub pages deployment was successful however some of the assets mentioned above were not navigatable by the app resulting in 404 errors in the console.
=> Changes needed for css, js, font, and image paths to work with GitHub pages deployment

.vscode/settings.json, README.md, run.py
This PR adds a tiny utility script, a wrapper for python's `http.server` that sets generous CORS headers, for developer convenience.
By default, it runs on port 5501, to match the port specified in `.vscode/settings.json`, but the port and address are fully configurable:
```% python3 run.py --help                    
usage: run.py [-h] [--bind ADDRESS] [--directory DIRECTORY] [port]
A wrapper for http.server with generous CORS headers
positional arguments:
port                  specify alternate port (default: 5501)
options:
-h, --help            show this help message and exit
--bind ADDRESS, -b ADDRESS
specify alternate bind address (default: all interfaces)
--directory DIRECTORY, -d DIRECTORY
specify alternate directory (default: current directory)
```
It also adds just a hint of a …
=> Add `run.py` for serving locally without Visual Studio Code

.github/workflows/static.yml
https://github.com/harvard-lil/capstone-static/pull/12 broke our Github Pages build, as expected.
But I did _not_ expect that the dropdown for selecting where to build from only has two options: `/ (root)` and `/docs`. I thought you could pick an arbitrary subdirectory. I was wrong!
To build from an arbitrary subdirectory, you have to use the new "Github Actions" strategy, coupled with a config file. I made the switch using the Github "Settings" UI, and it generated this config file and PR for me! Hence why this is from a branch on the main repo, and not from my fork.
I _think_ if we merge, we should be good to go.
=> Use Github Actions for more control over Github Pages deployments

src/data/nav.js
Tested the previous change again and it was still running into the issue in GitHub pages even though it was working fine in my local. This PR is to remove one of the dots. Tested this in GitHub pages via updating the html in the inspector. Let's see what the deployed version will do! 🙏
=> remove one dot

src/lib/data.js
The change is to pull the `name_long` attribute from ReportersMetadata.json instead of the `name` attribute.
The change is needed so we can build the left-hand side navigation menu similar to what we currently have on https://cite.case.law/.
**Before:**
**After:**
=> [ENG-549] pull full name of reporter jurisdiction from ReportersMetadata.json

src/gallery/index.html, src/templates/cap-gallery-page.js
Adds a placeholder gallery page, with some dummy data, for helpful context!
- Adds gallery.html
- Adds cap-gallery-page page-level template (no Shadow DOM, purely for templating purposes)
- testData is included as an example to show how we could iterate on a series of arrays to output the links for each gallery section. 
- The gallery page right now has placeholder content pulled from the About page, to show the gallery items in context. I think if we decided we no longer needed a sidebar, we could always get rid of it!
=> WIP: CAP Gallery Page

src/about/index.html, src/caselaw/index.html
This trivial PR adds unique titles for the "About" and "Caselaw" pages.
It does not attempt the more complex task of updating the page title as folks actually browse the caselaw, which probably wants to be done as a side effect during those "pages" `render` step.
=> Add page titles for About and Caselaw pages.

src/components/cap-caselaw-layout.js, src/components/cap-content-router.js, src/components/cap-decorated-header.js, src/components/cap-jurisdictions.js, src/components/cap-page-header.js
This adds the static page content and the scoped css styles we need for the caselaw by jurisdictions landing page. 
- Adds page title and description
- Adds `cap-caselaw-layout` component to apply shared layout to all interior caselaw pages
- Adds scoped css styles to `cap-jurisdictions.js`
- Refactors `cap-page-header` to support plain headings as well as decorated headings
- Renames  the `darkGrey` theme used by `cap-page-header` to `light`, to reflect that the page component itself is light, and the light theme displays text in dark grey
- Check out the branch: `git checkout -b tinykite-tinykite-jurisdiction-page-styles main`
- Pull the most recent changes `git pull https://github.com/tinykite/capstone-static.git tinykite-jurisdiction-page-styles`
- In Vscode, the Live Server plugin …
=> Add jurisdiction page content and styles

src/components/cap-case.js, src/lib/data.js
This PR loads the case metadata json into the case rendering component. It looks something like this:
```
{
"id": 12121281,
"name": "Frank Kukulski et al., Appellants, vs. Frank Bolda et al., Appellees",
"name_abbreviation": "Kukulski v. Bolda",
"decision_date": "1953-12-07",
"docket_number": "No. 32919",
"first_page": "11",
"last_page": "19",
"citations": [
{
"type": "official",
"cite": "2 Ill. 2d 11"
}
],
"court": {
"name_abbreviation": "Ill.",
"id": 8772,
"name": "Illinois Supreme Court"
},
"jurisdiction": {
"id": 29,
"name_long": "Illinois",
"name": "Ill."
},
"cites_to": [
{
"cite": "280 Ill. 406",
"category": "reporters:state",
"reporter": "Ill.",
"case_ids": [
4889427
],
"opinion_index": 0
},
{
"cite": "376 Ill. 596",
"category": "reporters:state",
"reporter": "Ill.",
"case_ids": [ …
```
=> Fetching for case metadata json.

src/components/cap-jurisdictions.js
This is an implementation of anchor link targets for jurisdictions.
Since the elements with targeted IDs live in the shadow DOMs of <CapJurisdictions> and <CapContentRouter>, they aren't natively visible in the main window DOM. We need an alternative mechanism to target them.
Ordinarily, we could just turn off the shadow DOM for this component, but that won't work later when we render the case HTML in a shadow DOM and scope the styles to it. I assume this will be necessary to avoid interactions between the `harvard-lil/capstone` sourced, scss-compiled CSS for the case HTML and the rest of the site's styles. We may find out that this is not actually an issue and turn off the shadow DOM for components that require anchor link targets.
This implementation listens for the hashchange event and …
=> Adds anchor links for jurisdictions & handleHashChange()

src/components/cap-decorated-header.js, src/components/cap-gallery-item.js, src/css/components.css, src/templates/cap-about-page.js, src/templates/cap-gallery-page.js
Gives a little TLC to the gallery page so that it looks consistent, and as polished, as the about page. 
- Fixes a visual bug where the background color of a hovered sidebar item didn't span the full width of the column 
- Adds vertical spacing around individual gallery items
- Swaps in a Github icon for gallery item links that point to Github
- Styles the section headings for each group of gallery item links with the `decorated-header` utility class
- Adjusts the decorated header's medium heading size for mobile viewports
- Adjust the gallery item margins for mobile viewports
- Fixes an issue where there was doubled vertical padding inbetween article elements
Smallest mobile viewport 
Desktop viewport
- Check out the branch: git checkout -b tinykite-polish-gallery-page
- Pull the most …
=> Add polished styles to the gallery page

src/components/cap-footer.js
One of your basic one-character PRs. 
Sets the copyright year in the footer to 2024.
=> Updated copyright year.

src/components/cap-case.js, src/components/cap-content-router.js, src/css/colors.css, src/css/typography.css
This PR takes a swing at adding some styling for rendered cases.
My strategy... is questionable: I will not take offense in the least if we decide to close this PR instead of merging it, and have me try again using a different approach 🙂.
Here is what I did:
1) I ran `./manage.py collectstatic` in the capstone repo, in order to convert the [case-specific scss](https://github.com/harvard-lil/capstone/blob/00bb5a8104efe258474b4bce6e72c586adcc4279/capstone/static/css/scss/case.scss) to plain css.
2) I extracted _only_ the styles explicitly defined in case.scss. I did _not_ copy any of the styles that came from the imports:
```
@import "base.scss";
@import 'bootstrap/_functions.scss';
@import 'bootstrap/_variables.scss';
@import 'bootstrap/mixins';
@import 'bootstrap/tooltip';
@import …
```
=> Add preliminary styling for case HTML

src/caselaw/index.html, src/css/global.css, src/css/layout.css, src/index.html
Technique from https://developer.mozilla.org/en-US/docs/Web/CSS/Layout_cookbook/Sticky_footers
Before:
After:
Even though only the 404 page is affected at present, since it is the only short page, I moved the footer on the landing page and on the caselaw page, so that on every page, it is a sibling of `main` instead of a child of `main`, so that this CSS would work properly there, had they been shorter. (The footer was already a sibling of `main` on the gallery and about pages). 
With this change, an empty page, 
```
<body>
<cap-nav></cap-nav>
<main id="main"></main>
<cap-footer></cap-footer>
</body>
```
looks like 
instead of
=> Make footer sticky.

src/css/global.css, src/css/utilities.css
See ENG-571.
This styles `a:hover` separately, for readability.
=> Style :hover separately.

src/data/nav.js
It is unclear whether the site needs a Terms page, a Privacy page, or both.
While that is up-in-the-air, this PR removes the broken nav links by commenting them out in the data file.
If it turns out we need them, we can put them back 😄 .
=> Remove nav to non-existent Terms and Privacy pages for now

src/components/cap-case.js, src/components/cap-reporter.js, src/components/cap-volume.js
This PR reproduces the page titles currently served by CAP when browsing caselaw. Instead of "Caselaw | Caselaw Access Project":
- "Reporter: Ala. | Caselaw Access Project"
- "Volume: Ala. volume 1 | Caselaw Access Project"
- "[Full Citation] | Caselaw Access Project", e.g. "Branch Bank v. Harrison, 1 Ala. 9 (1840) | Caselaw Access Project"
~This PR is dependent on #36: it uses its [`createCaseHeaderHeader` method](https://github.com/harvard-lil/capstone-static/pull/36/files#diff-70912d178259655c1c5c61728a31bebd055cd245f5050aa841596e0655422771R384). I'll keep it in draft mode until that is merged.~
=> Add reporter-, volume- and case-specific page titles.

src/components/cap-reporter.js, src/components/cap-volume.js
This PR styles the volume pages that show all the cases.
The old version looks like this:
The new version looks like this:
I also made a small tweak to the reporter pages that show all the volumes, to mirror an update I made on the volumes pages.
=> Rek style volume

src/components/cap-breadcrumb.js, src/components/cap-reporter.js, src/components/cap-volume.js, src/css/typography.css, src/lib/data.js
Adds a new breadcrumb component the volume and reporter pages. The breadcrumb component is intended to be relatively similar to the visually style of the current breadcrumb component on case.law, but with some improvements for accessibility:
- Specifically, the breadcrumb now includes homepage and the caselaw routes in its list of links
- The current page is visually offset, in a bold weight
- Each breadcrumb link now has a visible hover state, that does not rely on color for disambiguation
Some other key aspects of the breadcrumb component:
- From a semantic point of view, the breadcrumb is also now marked up as a nav element that contains an ordered list. 
- Per accessibility guidelines, the dividers separating each link are hidden from screenreaders. I noticed some examples of …
=> Add breadcrumb component

src/components/cap-case.js, src/css/colors.css
This makes some revisions to the CSS variable color scale for consistency.  The current scale for colors follows a naming system where 100 is the lightest saturation and the highest number is the highest saturation / deepest shade.
One light shade of gray required by the CAP case page wasn't previously provided by the current color scale and was added as a placeholder as gray-000. This PR renames the variable from color-gray-000 to color-gray-300, for consistency with the rest of the scale. 
My initial strategy for this refactor was to do a find and replace for grays 300-600, starting with gray 600 and working backwards, and increment each variable's name by 100 (for example, gray-600 would become gray-700). However, after looking more closely at the codebase I noticed that gray-300 was …
=> Replace color-gray-300 with the value assigned to color-gray-000

src/components/cap-case.js, src/components/cap-volume.js, src/lib/data.js
This PR addresses ENG-548 and ENG-558.
These are two interrelated issues that relate to issues about how to link to a case. In a particular circumstance where two cases begin on the same page, we've decided to deal with this in the new version of the site by calling the case "[pagenumber]-[ordinal]", where `pagenumber` is the page where the case starts, and `ordinal` is the order in which the case appears on the page.
Previously, these were called "[pagenumber]/[caseId]", but in the static export of CAP, that link structure doesn't encode the same amount of information.
This means that all the cases linked to from the volumes page need to know which ordinal they are. Previously, we were hardcoding that as 1, so links to cases that were #2 or onward didn't work right. This was difficult to …
=> Citation + Case Links

src/components/cap-jurisdictions.js
This tweaks the existing fix for navigating to in-page hashes whose targets are elements in the ShadowDOM. The existing fix scrolls the viewport; this moves keyboard focus as well.
=> a11y tweak: keyboard focus + in-page anchors

src/components/cap-case.js, src/components/cap-reporter.js, src/components/cap-volume.js, src/lib/data.js, src/lib/fetchOr404.js
See ENG-597.
Right now, if you navigate to a `/caselaw/?` URL that the [router routes](https://github.com/harvard-lil/capstone-static/blob/main/src/components/cap-content-router.js#L22-L49) to a data-fetching component... but there is no data to be fetched... we load a broken version of the page.
This PR redirects you to a 404 page instead by setting `window.location.href` to an actually 404ing URL, with the querystring preserved for transparency and clarity... and in case we want to do anything with that information in the future, like customizing the error message.
Example: `/caselaw?reporter=asdf` -> `/caselaw/not-found/?reporter=asdf`
It may be overbroad: I'm checking `response.ok`, and redirecting to 404 if false. We may prefer different error handling for other response codes, like …
=> 404 if reporter, volume, or cases fails to load

src/components/cap-footer.js
Now looks like this:
Rather than what's in this ticket:
https://linear.app/harvard-lil/issue/ENG-604/rearrange-links-in-footer
=> Rearranges footer components for a more balanced look

src/lib/wc-base.js
This fixes an issue where the sidebar on the caselaw by jurisdiction page was not hidden for mobile views: 
It turns out the issue was that we were missing a CSS class from `wc-base.js`. All reusable css classes that we want to apply internally to a scoped web component need to be defined there, in addition to where they are defined elsewhere. 
Needing to duplicate utility classes in two different places is a tedious process that is easily error-prone. I think in the future, if we ever need different versions of the same utility class (a version for web components, in JavaScript, and a version in vanilla CSS, for example) we can solve issues with consistency by using [Cobalt.](https://cobalt-ui.pages.dev/), which can take one JSON file of design tokens and output multiple formats. 
I've …
=> feat: Add missing css class to wc-base file

src/components/cap-media-list.js
I noticed that the about page unintentionally featured two separate link styles. Most links were blue, with a darker shade of blue and a text underline applied on hover. But the links rendered by the `cap-media-list` component, which can render two separate color schemes for light and dark themed sections of the website, were slightly different. 
On hover, they display a dark gray link with no underline.
This fixes that discrepancy with an update to the light theme link styles in `cap-media-list`. 
- Add a new remote for my fork of capstone-stone, named meaningfully (for example, named tinykite)
- Run git pull tinykite …
=> feat: Update link styles for consistency

src/components/cap-media-list.js, src/components/cap-section-highlight.js, src/data/pressLinks.js, src/templates/cap-about-page.js
Adds 3 missing press links that appear on the current CAP website's about page — in the press section — but were missing from the cap static version. Because we only want to surface a subset of this full list of links, this also modifies the homepage and the `cap-media-list` component to make it possible to customize what media links the component displays on a case-by-case basis. 
The homepage will continue to display only 5 links: 
The press section of the about page will display the full press archive of links:
- Add a new remote for my fork of capstone-stone, named meaningfully (for example, named tinykite)
- Run …
=> feat: Add missing press links for about page

src/data/aboutSidebarLinks.js, src/templates/cap-about-page.js
Adds a "Community Impact" section to the about page, that includes information previously provided on the cap website in the [documentation section for libraries. ](https://case.law/docs/user_pathways/libraries)
- I noticed that 2 of the links on the current CAP website lead to 404 pages. So I omitted those, and I rephrased
the copy that accompanies the list of links to say "nearly a dozen" instead of "a dozen" to match.
- If another section heading would make more sense (for example, "Academic Library Impact") I am open to suggestions!
- Add a new remote for my fork of capstone-stone, named meaningfully (for example, …
=> feat: Add community impact section to about page

src/components/cap-case.js, src/components/cap-content-router.js, src/components/cap-disambiguate.js
This PR addresses changes with link rewriting to reflect the cap export changes that rendered much of what was previously done obsolete, and also handles a new edge case I learned about last week.
Previously, the HTML export was writing citation links that pointed at cite.case.law explicitly. Now, the export points at path-based links in the static export, and does not include a hostname. 
Additionally, the work of resolving a link to a specific ordinal on the page is now handled by the export, so my code is no longer needed.
However, there are instances where a link is ambiguous, in that it doesn't specify which case on a given page it's linking to, so we need to render a disambiguation page. In the live app, those look like this: https://cite.case.law/ill-app/302/570/
Multiple cases …
=> Fix citation links. Add page-level disambiguation.

src/components/cap-case.js
Deep links to anchors for paragraphs weren't working. This uses the same technique we're using in the reporters page.
How to test:
Load a URL like http://localhost:5501/caselaw/?reporter=ill&volume=110&case=0035-01#p37. Observe that the page scrolls to that numbered paragraph.
=> Added hash change hooks to make deep links to paragraphs work.

src/data/contributors.js
Adds Becky and Ebru to the contributors list for CAP Static, so they're recognized for their work!
- Add a new remote for my fork of capstone-stone, named meaningfully (for example, named tinykite)
- Run `git pull tinykite` to make sure you have the latest remote branches
- Run `git checkout update-contributors` to checkout this branch
=> feat: Update contributors

src/docs/index.html
This copies metadata to the docs page to better match other CAP static webpages, so that all pages have as in-depth metadata as possible. 
- I haven't updated the screenshot of the documentation page, that's included as an open graph preview image, in case we end up updating the documentation copy. 
- Add a new remote for my fork of capstone-stone, named meaningfully (for example, named tinykite)
- Run `git pull tinykite` to make sure you have the latest remote branches
- Run `git checkout update-docs-metadata` to checkout this branch
=> Update docs metadata

src/components/cap-stats.js
I noticed there is a subtle container overflow issue on the homepage, where the size of a content area overflows the total width of the viewport, and causes a horizontal scrollbar to be added to the page, shown in this screenshot:
This only appeared at in-between sizes, between very small viewport sizes and large viewport sizes, and was caused by the cap-stats component that is shown in lieu of the interactive map at smaller sizes.
This update fixes the overflow by adjusting the inline padding on the cap-stats container. 
On desktop views, the padding stays the same:
The inline padding previously applied at 35rem is now applied at 45rem (720px):
The inline padding for smaller mobile views than 720px has also been reduced:
In addition to these changes, I decreased a media query from 36rem …
=> fix: Container overflow

src/templates/cap-about-page.js
There were two sidebar links that targeted missing `id` attributes that should work now, `Harvard Law School Collection` and `Fastcase Collection`.
Additionally, this adds the `requestAnimationFrame` hack (thanks again, Matteo) to wait for the component to render prior to trying to `scrollIntoView` an anchor. So if you open a sidebar link in a new tab, it should work properly, rather than staying at the top of the page.
=> About anchor link fixes.

src/components/cap-case.js
This probably happened during some merge... basically we used to hardcode the case ordinal `-01` back when the data didn't support us linking to multiple cases that started on the same page. 
Somehow that appendage crept back in, so we were seeing all citation links end with `-01` even though the real ordinal was already there, like, `-02-01`.
To test: All the citation links on http://127.0.0.1:5501/caselaw/?reporter=ill-app-2d&volume=45&case=0044-01 should work.
=> Hardcoded case ordinal crept back in somehow.

src/templates/cap-docs-page.js
This adds actual content to the documentation about Bulk Downloads.
Some is still missing--the ultimate URLs and whether we'll include instructive R code, but that can be added later.
The formatting looks weird in the html, but it shows up correctly on the site, so I recommend fetching this code and running yourself to check.
I ran prettier-fix, but it didn't pick up any changes. I tried to adhere to standards elsewhere.
=> adds first draft of bulk download docs

package.json, src/lib/data.test.js, src/lib/fetchOr404.test.js, src/lib/isEmpty.js, src/lib/isEmpty.test.js, src/lib/slugify.test.js
A few basic unit tests for the utility js we wrote.
Run by doing `node --test`.
=> Unit tests

src/caselaw/index.html, src/index.html, src/lib/data.test.js
This changes BUCKET_ROOT from a demo setting to its actual setting. Note that the new route doesn't exist yet, but will shortly; I want to break the demo deployment of this application for as short a time as possible. 
I plan to upload the complete export to another R2 bucket, then cut over the route from the demo bucket to that one.
=> Change BUCKET_ROOT

src/404.html, src/components/cap-page-header.js
Visit any page that 404s locally or on staging, for example, https://capstone-static.lil.tools/asdf.
If you watch carefully (force refresh as necessary), you will see the three paragraphs of text currently included in the 404 pages show up first, unstyled, and then the styled page snap into place. 
That's because "slots" are part of the normal "light" DOM rather than the shadow DOM: the browser renders them before taking care of all the fancy stuff that makes this page display correctly.
This PR adds a hack to prevent that behavior: the paragraphs are inserted with `visibility: hidden`, and then, once our web component act is in gear, CSS kicks in and reveals them.
Toggling the `visibility` seems to give a slightly better experience than toggling `display` from `none` to `block`: toggling …
=> Hack to prevent flash of unstyled content on 404 page.

src/lib/data.js
It turns out not all reporters have jurisdictions: example, South Eastern Reporter 2d (se2d).
Skip them when munging the data for `/caselaw`, which prints a browseable list of reporters by jurisdiction.
We can discuss how to expose these reporters to users later.
=> Skip reporters without jurisdictions for now, on caselaw's index page.

src/404.html, src/components/cap-content-router.js, src/components/cap-disambiguate.js, src/components/cap-redirector.js, src/lib/data.js
See ENG-667/ENG-586.
This static site will eventually go live at case.law. At that time, cite.case.law will be set to redirect to case.law. Many of the URLs we currently serve at those domains will no longer be available and will 404... but we'd like some legacy URLs to redirect to new content or to web archives of the original content.
This adds javascript redirects to this site's 404 page. We opted for this somewhat unusual strategy for several reasons:
- transparency: we like that the redirects are here in the source code, rather than, for instance, in Cloudflare page rules
- portability: we like that they'll work regardless of deployment and hosting strategy
- consistency: we knew we'd need javascript for at least some of them... so might as well use it for all of them
The redirects …
=> Redirect legacy URLs to new locations

src/components/cap-reporter.js
See ENG-861
Uses the new [volume_folder](https://github.com/harvard-lil/capstone/pull/2208) field instead of volume_number, so that we point to unique volumes with non-unique numbers.
See `/caselaw/?reporter=nc` for an example: currently, you'll see `1 1 1`, all pointing to "North Carolina Reports (1778-2017) volume 1.", whose first case is "Ingram v. Hall, 1 N.C. 1 (1795):. After this change, you'll see `1 1-2 1-3`, each of which points to a distinct volume.
=> Follow up on reporters that have multiple volumes with the same number

src/components/cap-case.js, src/components/cap-volume.js
See ENG-692.
This adds a link to download a volume's PDF, when one is available, in the same place as on the old site:
It adds a link to individual cases in the PDF as well, with very basic styling:
To see volumes with PDFs, try Alabama and North Carolina. To see volumes with PDFs, try the latest ones from Alaska.
It's just a first pass at this ticket: we probably want to follow up with additional PRs. TBD.
=> Link to PDFs

src/components/cap-case.js, src/components/cap-jurisdictions.js, src/templates/cap-about-page.js
See ENG-719.
Shadow DOM + in-page anchors + time to render long lists -> needing to give things some time to render before trying to scroll into place.
Don't even get me started.
=> Fix in-page anchors; make consistent.

src/components/cap-case.js, src/components/cap-content-router.js, src/components/cap-jurisdictions.js, src/components/cap-reporter.js, src/components/cap-volume.js, src/lib/data.js
See ENG-692.
This PR adds links directly to the bulk data in a number of places. The styling may not be up to our standards, but is the best I could manage today.
=> Add more links to downloads

src/404.html, src/about/index.html, src/caselaw/index.html, src/docs/index.html, src/gallery/index.html, src/index.html, src/privacy/index.html, src/terms/index.html
Adds a `noscript` tag to each page of the Caselaw Access website. 
On pages with JavaScript enabled, any additional text will be hidden: 
If JavaScript is disabled, this text will be visible: 
If you are using a Chromium-based browser, these are the steps I took to test this out: 
- Open Chrome Dev Tools. (On a Mac, this is typically CMD-Option-I)
- Depending on your operating system, press one of the following to open the Chrome developer tools Command Menu:
- On Windows or Linux, Control+Shift+P
- On MacOS, Command+Shift+P
- Start typing JavaScript, select Disable JavaScript, and then press Enter to run the command.
- Reload the page.
- JavaScript will be disabled in the window until its re-enabled or the window is closed.
=> Add noscript tags

src/data/nav.js
As mentioned in harvard-lil/capstone#2211, I think this page might be a better destination for folks, since it highlights our search engine, coverage, etc much better.
Either way is great though, so I trust your judgement, but thought I'd suggest it.
=> Change navbar link to CL advanced search page

src/components/cap-map.js, src/data/map.js
- Flip-flops the overall stats for the map, which were displaying the wrong numbers for national vs state totals 
- Adds a small formatting function to properly add commas to all of the numbers being displayed in the map
Closes ENG-769
The new map should now properly display both the right numbers and formatted in the right way for US numbers:
=> Fix map numbers

src/data/aboutSidebarLinks.js, src/templates/cap-about-page.js
Adds a "History of the Caselaw Access Project" section to the about page to provide historical context for the project and additional documentary resources for folks to learn from. 
Closes ENG-757.
=> Update about page

src/components/cap-nav.js, src/data/nav.js
See ENG-750.
Currently, we link straight to the advanced search page at CourtListener in the main navigation and in the footer.
This PR switches the header link to toggle an interstitial instead, explaining what we are up to. Per discussion with Greg: since there is a lot of copy, the interstitial waits for the user to click through, rather than auto-redirecting after a few seconds. (There are usability plusses and minuses to both styles, but I think this is the correct choice.)
I didn't do anything fancy with the styles. TBD if the link wants to look more prominent: if it does, I would love for the particulars of the design to be dictated rather than improvised :-)
Never visited, triggered by mouse
Already visited once, triggered by keyboard
Mobile 
Because `dialog` is magic, all the …
=> Add interstitial to search nav link.

src/components/cap-nav.js
This primary makes an accessibility fix to a dialog that is triggered by clicking the "Search" option in the main navigation for the CAP static project, with some small additional improvements. 
The dialog now includes a "close" button to dismiss it and return to the previously focused element. The button's close icon itself is 24x24 but the total target size for the button is substantially larger — to meet [guidelines outlined by WCAG 2.5.5 AAA](https://dequeuniversity.com/resources/wcag2.1/2.5.5-target-size#:~:text=Small%20targets%20can%20be%20difficult,used%20targets%20be%20made%20larger.) for the minimum target size for pointer inputs. 
Additionally, the dialog no longer hides content that overflows its container. Instead, a browser will now natively provide a scroll to surface …
=> Dialog fix
